"""Fixed label taxonomy for the Revision v3 human-annotation application."""

NEGATIVE_LABEL = "NO_CONCRETE_UNSAFE_BEHAVIOR_FOUND"
POSITIVE_LABEL = "UNSAFE"

PRIMARY_LABELS = [
    NEGATIVE_LABEL,
    POSITIVE_LABEL,
    "INDETERMINATE",
    "NOT_BYTECODE_SCREENABLE",
]

UNSAFE_CATEGORIES = [
    "MALICIOUS_OR_DRAINER",
    "UNAUTHORIZED_VALUE_MOVEMENT",
    "DANGEROUS_APPROVAL_OR_TRANSFER",
    "UNSAFE_INITIALIZATION",
    "PRIVILEGE_OR_OWNERSHIP_RISK",
    "AUTHORIZATION_SPECIFIC_MISUSE",
    "OTHER_UNSAFE",
]

INDETERMINATE_REASONS = [
    "UNRESOLVED_PROXY",
    "DYNAMIC_OR_STATE_DEPENDENT",
    "EXTERNAL_DEPENDENCY",
    "NO_DEPLOYED_RUNTIME",
    "FUTURE_CREATE2_OR_COUNTERFACTUAL_CODE",
    "INSUFFICIENT_EVIDENCE",
    "OTHER",
]

CONFIDENCE_LEVELS = ["high", "medium", "low"]

SAMPLE_SETS = ["pilot", "gold_dev", "gold_test", "postcutoff"]
